# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Req < Formula
  desc ""
  homepage "https://github.com/ernesto27/homebrew-tools"
  version "1.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ernesto27/req/releases/download/v1.0.7/req_Darwin_arm64.tar.gz"
      sha256 "7c9fab6d100ffbeeeb0f3d829ca8934038e5893fc8f48e5b4763b31a3eb78c79"

      def install
        bin.install "req"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ernesto27/req/releases/download/v1.0.7/req_Darwin_x86_64.tar.gz"
      sha256 "f5c6be12aef89dbe0cb4c8fc1a46be01a0fa32b1d7436a780a33e6f08ec49d47"

      def install
        bin.install "req"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ernesto27/req/releases/download/v1.0.7/req_Linux_arm64.tar.gz"
      sha256 "2601ff93bc728a8ebb95d6af70c646734e5e3fa78648e11a17014240cab3529d"

      def install
        bin.install "req"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ernesto27/req/releases/download/v1.0.7/req_Linux_x86_64.tar.gz"
      sha256 "d287079819eff76c727abd1013765d0102c3e1ee82230651b1268694f1323e8f"

      def install
        bin.install "req"
      end
    end
  end
end
