# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Req < Formula
  desc ""
  homepage "https://github.com/ernesto27/homebrew-tools"
  version "1.0.10"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ernesto27/req/releases/download/v1.0.10/req_Darwin_arm64.tar.gz"
      sha256 "a255a2cfe4c598ade643a96cd5c1b4f636231c4940590e5dc6b513c3dd1f3a8f"

      def install
        bin.install "req"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ernesto27/req/releases/download/v1.0.10/req_Darwin_x86_64.tar.gz"
      sha256 "e9a40eff086d7596ad189a851ea207347c53d3447429620c487a596877c385ae"

      def install
        bin.install "req"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ernesto27/req/releases/download/v1.0.10/req_Linux_arm64.tar.gz"
      sha256 "afe892603f88a08102f88b87abb384568b804e089f7abeed22f2cf0de706c342"

      def install
        bin.install "req"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ernesto27/req/releases/download/v1.0.10/req_Linux_x86_64.tar.gz"
      sha256 "e6b8a8ec4a121e083843815be241f1bc57d1415ab26a6564b6f4a61b3e39e18d"

      def install
        bin.install "req"
      end
    end
  end
end
