# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stui < Formula
  desc ""
  homepage "https://github.com/ernesto27/homebrew-tools"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ernesto27/stui/releases/download/v0.0.5/stui_Darwin_arm64.tar.gz"
      sha256 "6fd96ef3d5130eed2fe58a59ff6cb7e66f5fa358e3836f573a964b29dfd61b9d"

      def install
        bin.install "stui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ernesto27/stui/releases/download/v0.0.5/stui_Darwin_x86_64.tar.gz"
      sha256 "b7e06b6b4d1d35b11b053090da99b65dc7322cc6dd4a7b6bbc3b757deb9f3562"

      def install
        bin.install "stui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ernesto27/stui/releases/download/v0.0.5/stui_Linux_arm64.tar.gz"
      sha256 "6a4fd5286f5cea0a94c255f0f10f2b7284a8454a4a734f6bc6842355631b6e74"

      def install
        bin.install "stui"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ernesto27/stui/releases/download/v0.0.5/stui_Linux_x86_64.tar.gz"
      sha256 "7b60de1b09cd9cf3049376a9540bba0f5243d3dbac4825e78416c6582077fcc4"

      def install
        bin.install "stui"
      end
    end
  end
end
