# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tname < Formula
  desc ""
  homepage "https://github.com/ernesto27/homebrew-tools"
  version "0.0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ernesto27/tname/releases/download/v0.0.7/tname_Darwin_arm64.tar.gz"
      sha256 "bb5fec64ea0f1ab2ca06ac8e5f16a99c7f006e538ffa421a7d11151f6ef6d50a"

      def install
        bin.install "tname"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ernesto27/tname/releases/download/v0.0.7/tname_Darwin_x86_64.tar.gz"
      sha256 "edba713e7b3f1b0653c3fbcfaf198ef5820432cc01cd06e2c28811b8065485ce"

      def install
        bin.install "tname"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ernesto27/tname/releases/download/v0.0.7/tname_Linux_arm64.tar.gz"
      sha256 "20821adc8ca7d2309f683c8f7258e98cad8f3be5523bf711d0f902aecf9587d7"

      def install
        bin.install "tname"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ernesto27/tname/releases/download/v0.0.7/tname_Linux_x86_64.tar.gz"
      sha256 "aba06e30e84c189da38e789afc6da5402a897ff2a19945546317ae4ac6816d68"

      def install
        bin.install "tname"
      end
    end
  end
end
